global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
    # Example Slack or webhook configuration can go here
    # slack_configs:
    #   - api_url: "https://hooks.slack.com/services/..."
    #     channel: "#alerts"
    # webhook_configs:
    #   - url: "http://your-webhook-endpoint"
